---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  vars:
    command: "{{ command }}"
  tasks:
    - name: 'Run a command on a linux VM'
      shell: "{{ command }}"
      ignore_errors: true
      changed_when: false
      register: check_command
    - debug:
        msg: "{{ check_command.stdout }}"

